# This file can be used as a template for configs which shouldn't be public on
# GitHub. You can copy it, fill the variables that are relevant to you and
# rename it .secrets.toml - that's in .gitignore.

[psquash]
    squash_user_pk = "1337"
    squash_organization_pk = "1337"
    squash_session_id = "ek01333333333333333372xt"


